import { Refine } from "@refinedev/core";

export const resources = [
  {
    name: "Dashboard",
    list: "/dashboard",
    meta: { canDelete: true },
  },
  {
    name: "Cadastros",
  },
  {
    name: "Acesso",
  },

  // Cadastros Submenus
  {
    name: "users",
    list: "/users",
    create: "/users/create",
    edit: "/users/edit/:id",
    show: "/users/show/:id",
    icon: "👤",
    meta: { parent: "Cadastros", canDelete: true },
  },
  {
    name: "visitors",
    list: "/visitors",
    create: "/visitors/create",
    edit: "/visitors/edit/:id",
    show: "/visitors/show/:id",
    icon: "👥",
    meta: { parent: "Cadastros", canDelete: true },
  },  
  {
    name: "Grupos",
    list: "/groups",
    create: "/groups/create",
    edit: "/groups/edit/:id",
    show: "/groups/show/:id",
    icon: "👥",
    meta: { parent: "Cadastros", canDelete: true },
  },  
  {
    name: "Empresas",
    list: "/companies",
    create: "/companies/create",
    edit: "/companies/edit/:id",
    show: "/companies/show/:id",
    icon: "🏢",
    meta: { parent: "Cadastros", canDelete: true },
  },  
  {
    name: "Tipos de Créditos",
    list: "/companies",
    create: "/companies/create",
    edit: "/companies/edit/:id",
    show: "/companies/show/:id",
    icon: "💳",
    meta: { parent: "Cadastros", canDelete: true },
  },  
  {
    name: "Gerenciamento de Créditos",
    list: "/companies",
    create: "/companies/create",
    edit: "/companies/edit/:id",
    show: "/companies/show/:id",
    icon: "💳",
    meta: { parent: "Cadastros", canDelete: true },
  },  
  {
    name: "Cartões Provisórios",
    list: "/companies",
    create: "/companies/create",
    edit: "/companies/edit/:id",
    show: "/companies/show/:id",
    icon: "💳",
    meta: { parent: "Cadastros", canDelete: true },
  },  
  {
    name: "Veículos",
    list: "/companies",
    create: "/companies/create",
    edit: "/companies/edit/:id",
    show: "/companies/show/:id",
    icon: "🚗",
    meta: { parent: "Cadastros", canDelete: true },
  },  
  {
    name: "Estacionamentos",
    list: "/companies",
    create: "/companies/create",
    edit: "/companies/edit/:id",
    show: "/companies/show/:id",
    icon: "🚗",
    meta: { parent: "Cadastros", canDelete: true },
  },  

  // Acesso Submenus
  {
    name: "Áreas",
    list: "/areas",
    create: "/areas/create",
    edit: "/areas/edit/:id",
    show: "/areas/show/:id",
    icon: "📍",
    meta: { parent: "Acesso", canDelete: true },
  },
  {
    name: "Dispositivos",
    list: "/dispositivos",
    create: "/dispositivos/create",
    edit: "/dispositivos/edit/:id",
    show: "/dispositivos/show/:id",
    icon: "📟",
    meta: { parent: "Acesso", canDelete: true },
  },
  {
    name: "Horários",
    list: "/horarios",
    create: "/horarios/create",
    edit: "/horarios/edit/:id",
    show: "/horarios/show/:id",
    icon: "⏰",
    meta: { parent: "Acesso", canDelete: true },
  },
  {
    name: "Regras de Acesso",
    list: "/regras-de-acesso",
    create: "/regras-de-acesso/create",
    edit: "/regras-de-acesso/edit/:id",
    show: "/regras-de-acesso/show/:id",
    icon: "🔑",
    meta: { parent: "Acesso", canDelete: true },
  },
  {
    name: "Regras por Exceção",
    list: "/regras-por-excecao",
    create: "/regras-por-excecao/create",
    edit: "/regras-por-excecao/edit/:id",
    show: "/regras-por-excecao/show/:id",
    icon: "⚠️",
    meta: { parent: "Acesso", canDelete: true },
  },
  {
    name: "Regras de Veículos",
    list: "/regras-de-veiculos",
    create: "/regras-de-veiculos/create",
    edit: "/regras-de-veiculos/edit/:id",
    show: "/regras-de-veiculos/show/:id",
    icon: "🚗",
    meta: { parent: "Acesso", canDelete: true },
  },
  {
    name: "Inativação Programada",
    list: "/inativacao-programada",
    create: "/inativacao-programada/create",
    edit: "/inativacao-programada/edit/:id",
    show: "/inativacao-programada/show/:id",
    icon: "🛑",
    meta: { parent: "Acesso", canDelete: true },
  },
  {
    name: "Notificações",
    list: "/notificacoes",
    create: "/notificacoes/create",
    edit: "/notificacoes/edit/:id",
    show: "/notificacoes/show/:id",
    icon: "🔔",
    meta: { parent: "Acesso", canDelete: true },
  },
  {
    name: "Relatórios",
    list: "/relatorios",
    create: "/relatorios/create",
    edit: "/relatorios/edit/:id",
    show: "/relatorios/show/:id",
    icon: "📊",
    meta: { parent: "Acesso", canDelete: true },
  },
  {
    name: "Configurações",
    list: "/configuracoes",
    create: "/configuracoes/create",
    edit: "/configuracoes/edit/:id",
    show: "/configuracoes/show/:id",
    icon: "⚙️",
    meta: { parent: "Acesso", canDelete: true },
  },
];
